# traefik.toml
[api]
  dashboard = true 
  insecure = true

[global]
  checkNewVersion = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[log]
  filePath = "/log/traefik.log"
  format = "json"
  level = "DEBUG"

[accessLog]
  filePath = "/log/access.log"
  format = "json"

[providers]
  [providers.docker]
    exposedByDefault = false

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    ]

[certificatesResolvers]
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[certificatesResolvers.myresolver.acme]
email = "putyouremail@here"
storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
  provider = "ovh"
  delayBeforeCheck = 10
